package com.mycompany.automatedtellermachine;

import javax.swing.*;
import java.sql.*;

public class LoginActivity extends JFrame {
    
    String cardNumberEntered;
    String user;
    String receiverUserName;
    float amountBalance;
    float receiverBalance;

    public LoginActivity() {
        initComponents();
    }

    // Code auto-generated by the IDE
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        resetButton = new javax.swing.JButton();
        proceedButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        balanceInfoButton = new javax.swing.JButton();
        cashWithDrawalButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        debitHistoryButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        resetButton1 = new javax.swing.JButton();
        proceedButton1 = new javax.swing.JButton();
        goToDashboardButton = new javax.swing.JButton();
        exitFromWithdrawalButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        resetButton2 = new javax.swing.JButton();
        proceedButton2 = new javax.swing.JButton();
        goToDashboardButton1 = new javax.swing.JButton();
        exitFromWithdrawalButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        amountField2 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        amount1 = new javax.swing.JLabel();
        amount2 = new javax.swing.JLabel();
        amount3 = new javax.swing.JLabel();
        amount4 = new javax.swing.JLabel();
        amount5 = new javax.swing.JLabel();
        exitFromWithdrawalButton2 = new javax.swing.JButton();
        goToDashboardButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("State Bank of India");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\kisha\\Downloads\\sbi.png")); // NOI18N
        jLabel1.setText("State Bank Of India");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel4.setBackground(new java.awt.Color(102, 0, 153));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Welcome to the Automated Teller Machine");

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("YOUR PIN IS CONFIDENTIAL NOBODY SHOULD SEE THE PIN");

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("WHILE YOU ARE ENTERING IT. MAKE YOUR PIN MORE SECURE BY CHANGING IT FREQUENTLY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(409, 409, 409))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(316, 316, 316))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 0, 153));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Card Number: ");

        cardNumberField.setBackground(new java.awt.Color(255, 0, 255));
        cardNumberField.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        cardNumberField.setForeground(new java.awt.Color(102, 0, 253));
        cardNumberField.setName(""); // NOI18N

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Pin:");

        pinField.setBackground(new java.awt.Color(255, 0, 255));
        pinField.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        pinField.setForeground(new java.awt.Color(102, 0, 253));

        resetButton.setBackground(new java.awt.Color(255, 0, 255));
        resetButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        resetButton.setForeground(new java.awt.Color(102, 0, 153));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        proceedButton.setBackground(new java.awt.Color(255, 0, 255));
        proceedButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        proceedButton.setForeground(new java.awt.Color(102, 0, 153));
        proceedButton.setText("Proceed");
        proceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(proceedButton)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cardNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel6.setBackground(new java.awt.Color(102, 0, 153));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Welcome to the dashboard");

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("PLEASE CLICK THE EXIT BUTTON BEFORE LEAVING");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(375, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(498, 498, 498))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(365, 365, 365))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(102, 0, 153));

        balanceInfoButton.setBackground(new java.awt.Color(255, 0, 255));
        balanceInfoButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        balanceInfoButton.setForeground(new java.awt.Color(102, 0, 153));
        balanceInfoButton.setText("Balance Info");
        balanceInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInfoButtonActionPerformed(evt);
            }
        });

        cashWithDrawalButton.setBackground(new java.awt.Color(255, 0, 255));
        cashWithDrawalButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        cashWithDrawalButton.setForeground(new java.awt.Color(102, 0, 153));
        cashWithDrawalButton.setText("Cash Withdrawal");
        cashWithDrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashWithDrawalButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(204, 51, 0));
        exitButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        exitButton.setForeground(new java.awt.Color(102, 0, 153));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        transferButton.setBackground(new java.awt.Color(255, 0, 255));
        transferButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        transferButton.setForeground(new java.awt.Color(102, 0, 153));
        transferButton.setText("Transfer");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        debitHistoryButton.setBackground(new java.awt.Color(255, 0, 255));
        debitHistoryButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        debitHistoryButton.setForeground(new java.awt.Color(102, 0, 153));
        debitHistoryButton.setText("Debit History");
        debitHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitHistoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(507, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(transferButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cashWithDrawalButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(balanceInfoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debitHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(503, 503, 503))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(cashWithDrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(balanceInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(debitHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel9.setBackground(new java.awt.Color(102, 0, 153));

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 255));
        jLabel9.setText("Amount:");

        amountField.setBackground(new java.awt.Color(255, 0, 255));
        amountField.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        amountField.setForeground(new java.awt.Color(102, 0, 253));
        amountField.setName(""); // NOI18N

        resetButton1.setBackground(new java.awt.Color(255, 0, 255));
        resetButton1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        resetButton1.setForeground(new java.awt.Color(102, 0, 153));
        resetButton1.setText("Reset");
        resetButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton1ActionPerformed(evt);
            }
        });

        proceedButton1.setBackground(new java.awt.Color(255, 0, 255));
        proceedButton1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        proceedButton1.setForeground(new java.awt.Color(102, 0, 153));
        proceedButton1.setText("Proceed");
        proceedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButton1ActionPerformed(evt);
            }
        });

        goToDashboardButton.setBackground(new java.awt.Color(255, 0, 255));
        goToDashboardButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        goToDashboardButton.setForeground(new java.awt.Color(102, 0, 153));
        goToDashboardButton.setText("Go to Dashboard");
        goToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDashboardButtonActionPerformed(evt);
            }
        });

        exitFromWithdrawalButton.setBackground(new java.awt.Color(255, 0, 0));
        exitFromWithdrawalButton.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        exitFromWithdrawalButton.setForeground(new java.awt.Color(102, 0, 153));
        exitFromWithdrawalButton.setText("EXIT");
        exitFromWithdrawalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFromWithdrawalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(goToDashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(proceedButton1)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton1))
                            .addComponent(exitFromWithdrawalButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104)))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proceedButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goToDashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitFromWithdrawalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(102, 0, 153));

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 102));
        jLabel11.setText("Please enter the amount below. (The maximum limit per transaction is Rs. 20,000/-) ");

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("CLICK ON THE GO TO DASHBOARD BUTTON TO GO TO THE DASHBOARD");

        jLabel13.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("PLEASE MAKE SURE YOU CLICK THE EXIT BUTTON BEFORE LEAVING.");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(153, 153, 153))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(1, 1, 1)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab3", jPanel8);

        jPanel12.setBackground(new java.awt.Color(102, 0, 153));

        jLabel14.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 102));
        jLabel14.setText("Please enter the User Name and the amount you want to transfer below. ");

        jLabel15.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("SCAM ALERT: BANK NEVER ASKS FOR ANY OTP/PIN/CVV. IT'S ONLY FOR YOU.");

        jLabel16.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("DO NOT SHARE YOUR PIN/CVV/OTP WITH ANYONE.");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel15)
                .addGap(0, 165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(222, 222, 222))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(341, 341, 341))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(102, 0, 153));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 255));
        jLabel10.setText("Receiver's User Name:");

        userNameField.setBackground(new java.awt.Color(255, 0, 255));
        userNameField.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        userNameField.setForeground(new java.awt.Color(102, 0, 253));
        userNameField.setName(""); // NOI18N

        resetButton2.setBackground(new java.awt.Color(255, 0, 255));
        resetButton2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        resetButton2.setForeground(new java.awt.Color(102, 0, 153));
        resetButton2.setText("Reset");
        resetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton2ActionPerformed(evt);
            }
        });

        proceedButton2.setBackground(new java.awt.Color(255, 0, 255));
        proceedButton2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        proceedButton2.setForeground(new java.awt.Color(102, 0, 153));
        proceedButton2.setText("Proceed");
        proceedButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedButton2ActionPerformed(evt);
            }
        });

        goToDashboardButton1.setBackground(new java.awt.Color(255, 0, 255));
        goToDashboardButton1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        goToDashboardButton1.setForeground(new java.awt.Color(102, 0, 153));
        goToDashboardButton1.setText("Go to Dashboard");
        goToDashboardButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDashboardButton1ActionPerformed(evt);
            }
        });

        exitFromWithdrawalButton1.setBackground(new java.awt.Color(255, 0, 0));
        exitFromWithdrawalButton1.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        exitFromWithdrawalButton1.setForeground(new java.awt.Color(102, 0, 153));
        exitFromWithdrawalButton1.setText("EXIT");
        exitFromWithdrawalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFromWithdrawalButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 255));
        jLabel17.setText("Amount:");

        amountField2.setBackground(new java.awt.Color(255, 0, 255));
        amountField2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        amountField2.setForeground(new java.awt.Color(102, 0, 253));
        amountField2.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goToDashboardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(proceedButton2)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amountField2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resetButton2)))
                            .addComponent(exitFromWithdrawalButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(amountField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proceedButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(goToDashboardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitFromWithdrawalButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab4", jPanel11);

        jPanel15.setBackground(new java.awt.Color(102, 0, 153));

        jLabel18.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 102));
        jLabel18.setText("The table below shows the Debit History");

        jLabel19.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("PLEASE CLICK EXIT BEFORE LEAVING.");

        jLabel20.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 102));
        jLabel20.setText("THANK YOU FOR BANKING WITH US. HAVE A NICE DAY :)");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19)))
                        .addGap(422, 422, 422))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(320, 320, 320))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(102, 0, 153));

        jLabel21.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 255));
        jLabel21.setText("Debit History");

        jLabel22.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 255));
        jLabel22.setText("Date");

        jLabel23.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 255));
        jLabel23.setText("Time");

        jLabel24.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 255));
        jLabel24.setText("Amount Debited (Rs.)");

        date1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        date1.setForeground(new java.awt.Color(255, 0, 255));
        date1.setText("date1");

        date2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        date2.setForeground(new java.awt.Color(255, 0, 255));
        date2.setText("date2");

        date3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        date3.setForeground(new java.awt.Color(255, 0, 255));
        date3.setText("date3");

        date4.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        date4.setForeground(new java.awt.Color(255, 0, 255));
        date4.setText("date4");

        date5.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        date5.setForeground(new java.awt.Color(255, 0, 255));
        date5.setText("date5");

        time1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        time1.setForeground(new java.awt.Color(255, 0, 255));
        time1.setText("time1");

        time2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        time2.setForeground(new java.awt.Color(255, 0, 255));
        time2.setText("time2");

        time3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        time3.setForeground(new java.awt.Color(255, 0, 255));
        time3.setText("time3");

        time4.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        time4.setForeground(new java.awt.Color(255, 0, 255));
        time4.setText("time4");

        time5.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        time5.setForeground(new java.awt.Color(255, 0, 255));
        time5.setText("time5");

        amount1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        amount1.setForeground(new java.awt.Color(255, 0, 255));
        amount1.setText("amount1");

        amount2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        amount2.setForeground(new java.awt.Color(255, 0, 255));
        amount2.setText("amount2");

        amount3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        amount3.setForeground(new java.awt.Color(255, 0, 255));
        amount3.setText("amount3");

        amount4.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        amount4.setForeground(new java.awt.Color(255, 0, 255));
        amount4.setText("amount4");

        amount5.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        amount5.setForeground(new java.awt.Color(255, 0, 255));
        amount5.setText("amount5");

        exitFromWithdrawalButton2.setBackground(new java.awt.Color(255, 0, 0));
        exitFromWithdrawalButton2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        exitFromWithdrawalButton2.setForeground(new java.awt.Color(102, 0, 153));
        exitFromWithdrawalButton2.setText("EXIT");
        exitFromWithdrawalButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitFromWithdrawalButton2ActionPerformed(evt);
            }
        });

        goToDashboardButton2.setBackground(new java.awt.Color(255, 0, 255));
        goToDashboardButton2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        goToDashboardButton2.setForeground(new java.awt.Color(102, 0, 153));
        goToDashboardButton2.setText("Go to Dashboard");
        goToDashboardButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDashboardButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel16Layout.createSequentialGroup()
                                    .addGap(284, 284, 284)
                                    .addComponent(jLabel21))
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(202, 202, 202)
                                        .addComponent(jLabel23)
                                        .addGap(159, 159, 159)
                                        .addComponent(jLabel24))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(date3)
                                                .addComponent(date2)
                                                .addComponent(date4))
                                            .addComponent(date1)
                                            .addComponent(date5))
                                        .addGap(125, 125, 125)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(time5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(amount1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(amount2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(amount3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(amount4)
                                            .addComponent(amount5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitFromWithdrawalButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goToDashboardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(503, 503, 503))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(time1)
                    .addComponent(amount1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date2)
                    .addComponent(time2)
                    .addComponent(amount2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date3)
                    .addComponent(time3)
                    .addComponent(amount3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date4)
                    .addComponent(time4)
                    .addComponent(amount4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date5)
                    .addComponent(time5)
                    .addComponent(amount5))
                .addGap(28, 28, 28)
                .addComponent(goToDashboardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitFromWithdrawalButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("tab5", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButtonActionPerformed
        try {
            String pinString = String.valueOf(pinField.getPassword());
            String cardNumber = cardNumberField.getText();
            int pinFromPassField = Integer.parseInt(pinString);
            
            String Query = "Select * from userInfo where cardNumber = '" + cardNumber + "';" ;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "Kishan@1072");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            int pin = rs.getInt(3);
            String card = rs.getString(2);
            user = rs.getString(1);
                
            if(cardNumber.equals(card) && pinFromPassField == pin) {
                jTabbedPane1.setSelectedIndex(1);
                cardNumberField.setText("");
                pinField.setText("");
            }
            else if(cardNumber.equals(card) && pinFromPassField != pin){
                JOptionPane.showMessageDialog(this, "<html>The pin you entered is incorrect<br>Please Re-enter the pin</br></html>", "Invalid details entered", JOptionPane.WARNING_MESSAGE);
                pinField.setText("");
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid card number", "Invalid details entered", JOptionPane.WARNING_MESSAGE);
            cardNumberField.setText("");
            pinField.setText("");
        }
    }//GEN-LAST:event_proceedButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.cardNumberField.setText("");
        this.pinField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void balanceInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInfoButtonActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "Kishan@1072");
            String Query = "Select * from userInfo where name = '" + user + "';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            float balanceAmountFromDatabase = rs.getFloat(4);
            JOptionPane.showMessageDialog(this, "<html>The balance amount is Rs. <b>" + balanceAmountFromDatabase + "</br></html>", "Balance", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please retry logging in", "Something Went Wrong", JOptionPane.ERROR_MESSAGE);
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_balanceInfoButtonActionPerformed

    private void cashWithDrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashWithDrawalButtonActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_cashWithDrawalButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int result;
        result = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_transferButtonActionPerformed

    private void debitHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitHistoryButtonActionPerformed
        date1.setText("");
        date2.setText("");
        date3.setText("");
        date4.setText("");
        date5.setText("");
        
        time1.setText("");
        time2.setText("");
        time3.setText("");
        time4.setText("");
        time5.setText("");
        
        amount1.setText("");
        amount2.setText("");
        amount3.setText("");
        amount4.setText("");
        amount5.setText("");
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "Kishan@1072");
            String Query = "select * from " + user + " order by dt desc, tm desc;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            int i = 1;
            
            while(rs.next()) {
                if(i == 1) {
                    date1.setText(rs.getString(1));
                    time1.setText(rs.getString(2));
                    amount1.setText(Float.toString(rs.getFloat(3)));
                }
                else if(i == 2) {
                    date2.setText(rs.getString(1));
                    time2.setText(rs.getString(2));
                    amount2.setText(Float.toString(rs.getFloat(3)));
                }
                else if(i == 3) {
                    date3.setText(rs.getString(1));
                    time3.setText(rs.getString(2));
                    amount3.setText(Float.toString(rs.getFloat(3)));
                }
                else if(i == 4) {
                    date4.setText(rs.getString(1));
                    time4.setText(rs.getString(2));
                    amount4.setText(Float.toString(rs.getFloat(3)));
                }
                else if(i == 5) {
                    date5.setText(rs.getString(1));
                    time5.setText(rs.getString(2));
                    amount5.setText(Float.toString(rs.getFloat(3)));
                }
                else {
                    break;
                }
                i++;
            }
            jTabbedPane1.setSelectedIndex(4);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Something Went Wrong, Please Try again in a moment.");
        }
    }//GEN-LAST:event_debitHistoryButtonActionPerformed

    private void resetButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton1ActionPerformed
        amountField.setText("");
    }//GEN-LAST:event_resetButton1ActionPerformed

    private void proceedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButton1ActionPerformed
        float balanceAmountFromDatabase, amount;
        try {
            amount = Float.parseFloat(amountField.getText());
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "Kishan@1072");
            java.util.Date date = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
            String Query = "Select * from userInfo where name = '" + user + "';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            balanceAmountFromDatabase = rs.getFloat(4);
            amountBalance = balanceAmountFromDatabase;
            
            if(amount <= balanceAmountFromDatabase) {
                PreparedStatement ps = con.prepareStatement("insert into " + user + " values(?,?," + amount + ");");
                ps.setDate(1, sqlDate);
                ps.setTimestamp(2, sqlTime);
                ps.executeUpdate();
                String Query2;
                amountBalance -= amount;
                Query2 = "Update userInfo set balanceAmount = " + amountBalance + " where name = '" + user +"';";
                Statement stmt = con.createStatement();
                stmt.executeUpdate(Query2);
                JOptionPane.showMessageDialog(this, "<html>Tansaction Successfully Completed<br/><b>Please collect the amount before leaving</b></html>", "Success!", JOptionPane.INFORMATION_MESSAGE);
                jTabbedPane1.setSelectedIndex(0);
                ps.close();
            }
            else if(balanceAmountFromDatabase == 0 || amount > balanceAmountFromDatabase) {
                JOptionPane.showMessageDialog(this, "The account does not have sufficient balance!", "Insufficient balance!", JOptionPane.ERROR_MESSAGE);
                amountField.setText("");
            }
            con.close();
            amountField.setText("");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid amount");
        }
    }//GEN-LAST:event_proceedButton1ActionPerformed

    private void goToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDashboardButtonActionPerformed
        amountField.setText("");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_goToDashboardButtonActionPerformed

    private void exitFromWithdrawalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFromWithdrawalButtonActionPerformed
        int result;
        amountField.setText("");
        result = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_exitFromWithdrawalButtonActionPerformed

    private void resetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton2ActionPerformed
        userNameField.setText("");
        amountField2.setText("");
    }//GEN-LAST:event_resetButton2ActionPerformed

    private void proceedButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedButton2ActionPerformed
        receiverUserName = userNameField.getText();
        String amountEntered = amountField2.getText();
        float balanceAmountFromDatabase;
        float amountEnteredFloat = Float.parseFloat(amountEntered);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "Kishan@1072");
            
            java.util.Date date = new java.util.Date();
            java.sql.Date sqlDate = new java.sql.Date(date.getTime());
            java.sql.Timestamp sqlTime = new java.sql.Timestamp(date.getTime());
            
            String Query = "Select * from userInfo where name = '" + user + "';";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            rs.next();
            balanceAmountFromDatabase = rs.getFloat(4);
            amountBalance = balanceAmountFromDatabase;
            
            String Query1 = "Select * from userInfo where name = '" + receiverUserName + "';";
            Statement st1 = con.createStatement();
            ResultSet rs2 = st1.executeQuery(Query1);
            rs2.next();
            receiverBalance = rs2.getFloat(4);
            
            if(amountBalance >= amountEnteredFloat) {
                amountBalance -= amountEnteredFloat;
                receiverBalance += amountEnteredFloat;
                String Query2 = "Update userInfo set balanceAmount = " + amountBalance + " where name = '" + user + "';";
                String Query3 = "Update userInfo set balanceAmount = " + receiverBalance + " where name = '" + receiverUserName + "';";
                st.executeUpdate(Query2);
                st.executeUpdate(Query3);
                userNameField.setText("");
                amountField2.setText("");
                JOptionPane.showMessageDialog(this, "The Transaction is completed successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            PreparedStatement ps = con.prepareStatement("insert into " + user + " values(?,?," + amountEnteredFloat + ");");
            ps.setDate(1, sqlDate);
            ps.setTimestamp(2, sqlTime);
            ps.executeUpdate();
        }  
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "The User Name or amount entred is Invalid", "Invalid details", JOptionPane.ERROR_MESSAGE);
            userNameField.setText("");
            amountField2.setText("");
        }
    }//GEN-LAST:event_proceedButton2ActionPerformed

    private void goToDashboardButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDashboardButton1ActionPerformed
        userNameField.setText("");
        amountField2.setText("");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_goToDashboardButton1ActionPerformed

    private void exitFromWithdrawalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFromWithdrawalButton1ActionPerformed
        int result;
        userNameField.setText("");
        amountField2.setText("");
        result = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_exitFromWithdrawalButton1ActionPerformed

    private void exitFromWithdrawalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitFromWithdrawalButton2ActionPerformed
        int result;
        result = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Confirm Exit", JOptionPane.YES_NO_CANCEL_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_exitFromWithdrawalButton2ActionPerformed

    private void goToDashboardButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDashboardButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_goToDashboardButton2ActionPerformed

    public static void main(String args[]) {
        // Code auto-generated by the IDE
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount1;
    private javax.swing.JLabel amount2;
    private javax.swing.JLabel amount3;
    private javax.swing.JLabel amount4;
    private javax.swing.JLabel amount5;
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField amountField2;
    private javax.swing.JButton balanceInfoButton;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JButton cashWithDrawalButton;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JButton debitHistoryButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitFromWithdrawalButton;
    private javax.swing.JButton exitFromWithdrawalButton1;
    private javax.swing.JButton exitFromWithdrawalButton2;
    private javax.swing.JButton goToDashboardButton;
    private javax.swing.JButton goToDashboardButton1;
    private javax.swing.JButton goToDashboardButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton proceedButton;
    private javax.swing.JButton proceedButton1;
    private javax.swing.JButton proceedButton2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton resetButton1;
    private javax.swing.JButton resetButton2;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JButton transferButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
